/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package REU_Server;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

public class ServerTest {
    @Test 
    public void execute() {
		assertEquals(100, 100);
    }
}
